### ISSUE TITLE
On join client don't get some chunks loaded, server stops communicating with client and client disconnects

### ISSUE THREAD

**Issue by Whitebrim** [drbot7/DrMap#9]
https://pastebin.com/BwCcgybG
https://pastebin.com/AJY1FkS7

After server restart I can't login two times - not all chunks are loaded and I got kicked.
I have lots of maps on my Lobby server

Minecraft Pufferfish 1.19.2, BungeeCord
Plugins on Lobby server (19): BungeeGuard, BungeeTabListPlus, DeluxeHub, DrMap, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), KeepChunks, LuckPerms, nLogin, PlaceholderAPI, ProtocolLib, SimplePortals, SurvivalInvisiframes, Vault, VentureChat, WorldGuard, WorldGuardExtraFlags

![2022-08-20_13 55 16](https://user-images.githubusercontent.com/23287829/185742780-9880647f-dc55-4a89-ac7b-5c123c91be84.png)

**Comment by akdukaan** [comment]
Based on your thread dump, I think this might be a bug that was introduced in Pufferfish-29. If you downgrade to Pufferfish-28, does the issue still occur? 

You can download Pufferfish-28 from https://ci.pufferfish.host/job/Pufferfish-1.19/28/artifact/build/libs/pufferfish-paperclip-1.19.1-R0.1-SNAPSHOT-reobf.jar

**Comment by Whitebrim** [comment]
> Based on your stack trace, I think this might be a bug that was introduced in Pufferfish-29. If you downgrade to Pufferfish-28, does the issue still occur?
> 
> You can download Pufferfish-28 from https://ci.pufferfish.host/job/Pufferfish-1.19/28/artifact/build/libs/pufferfish-paperclip-1.19.1-R0.1-SNAPSHOT-reobf.jar

Pufferfish-28 is Minecraft 1.19.1 version, downgrading to previous minecraft version isn't an option for me, Should I write an issue to the Pufferfish github?

**Comment by akdukaan** [comment]
Oh, I didn’t know that. In that case, don’t downgrade. Opening an issue in the pufferfish GitHub would definitely help!

**Comment by akdukaan** [comment]
I tried to reproduce this with the plugins folder, world folder, startup flags, and server jar you used and wasn't able to. Not sure what else I can do. It might be something related to bungee which I didn't use in my testing. If you figure out more information on what exactly causes this, I can take another look.

For anyone else running into this problem, Whitebrim was able to stop the issue from happening by removing `--add-modules=jdk.incubator.vector` from the startup flags so that can be used as a temporary solution.
